# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/actions/gs702a/setup-makefiles.sh


PRODUCT_COPY_FILES += \
  vendor/actions/gs702a/proprietary/bin/applypatch:system/bin/applypatch \
  vendor/actions/gs702a/proprietary/bin/pfmnceserver:system/bin/pfmnceserver \
  vendor/actions/gs702a/proprietary/bin/recovery:system/bin/recovery \
  vendor/actions/gs702a/proprietary/bin/dosfslable:system/bin/dosfslable \
  vendor/actions/gs702a/proprietary/bin/bugreport:system/bin/bugreport \
  vendor/actions/gs702a/proprietary/bin/usbmond:system/bin/usbmond \
  vendor/actions/gs702a/proprietary/bin/rild:system/bin/rild \
  vendor/actions/gs702a/proprietary/bin/vold:system/bin/vold \
  vendor/actions/gs702a/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
  vendor/actions/gs702a/proprietary/etc/excluded-input-devices.xml:system/etc/excluded-input-devices.xml \
  vendor/actions/gs702a/proprietary/etc/gpu_config:system/etc/gpu_config \
  vendor/actions/gs702a/proprietary/etc/vold.fstab:system/etc/vold.fstab \
  vendor/actions/gs702a/proprietary/etc/vold.sdboot.fstab:system/etc/vold.sdboot.fstab \
  vendor/actions/gs702a/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
  vendor/actions/gs702a/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
  vendor/actions/gs702a/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
  vendor/actions/gs702a/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
  vendor/actions/gs702a/proprietary/lib/egl/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \
  vendor/actions/gs702a/proprietary/lib/egl/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \
  vendor/actions/gs702a/proprietary/lib/egl/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \
  vendor/actions/gs702a/proprietary/lib/adAAC.so:system/lib/adAAC.so \
  vendor/actions/gs702a/proprietary/lib/adAC3.so:system/lib/adAC3.so \
  vendor/actions/gs702a/proprietary/lib/adACELP.so:system/lib/adACELP.so \
  vendor/actions/gs702a/proprietary/lib/adAMR.so:system/lib/adAMR.so \
  vendor/actions/gs702a/proprietary/lib/adAPE.so:system/lib/adAPE.so \
  vendor/actions/gs702a/proprietary/lib/adAWB.so:system/lib/adAWB.so \
  vendor/actions/gs702a/proprietary/lib/adCOOK.so:system/lib/adCOOK.so \
  vendor/actions/gs702a/proprietary/lib/adDTS.so:system/lib/adDTS.so \
  vendor/actions/gs702a/proprietary/lib/adFLAC.so:system/lib/adFLAC.so \
  vendor/actions/gs702a/proprietary/lib/adMP3.so:system/lib/adMP3.so \
  vendor/actions/gs702a/proprietary/lib/adOGG.so:system/lib/adOGG.so \
  vendor/actions/gs702a/proprietary/lib/adPCM.so:system/lib/adPCM.so \
  vendor/actions/gs702a/proprietary/lib/adWMALSL.so:system/lib/adWMALSL.so \
  vendor/actions/gs702a/proprietary/lib/adWMAPRO.so:system/lib/adWMAPRO.so \
  vendor/actions/gs702a/proprietary/lib/adWMASTD.so:system/lib/adWMASTD.so \
  vendor/actions/gs702a/proprietary/lib/aeMP3.so:system/lib/aeMP3.so \
  vendor/actions/gs702a/proprietary/lib/aeWAV.so:system/lib/aeWAV.so \
  vendor/actions/gs702a/proprietary/lib/apAAC.so:system/lib/apAAC.so \
  vendor/actions/gs702a/proprietary/lib/apAC3.so:system/lib/apAC3.so \
  vendor/actions/gs702a/proprietary/lib/apAMR.so:system/lib/apAMR.so \
  vendor/actions/gs702a/proprietary/lib/apAPE.so:system/lib/apAPE.so \
  vendor/actions/gs702a/proprietary/lib/apDTS.so:system/lib/apDTS.so \
  vendor/actions/gs702a/proprietary/lib/apFLAC.so:system/lib/apFLAC.so \
  vendor/actions/gs702a/proprietary/lib/apMP3.so:system/lib/apMP3.so \
  vendor/actions/gs702a/proprietary/lib/apOGG.so:system/lib/apOGG.so \
  vendor/actions/gs702a/proprietary/lib/apRMA.so:system/lib/apRMA.so \
  vendor/actions/gs702a/proprietary/lib/apWAV.so:system/lib/apWAV.so \
  vendor/actions/gs702a/proprietary/lib/apWMA.so:system/lib/apWMA.so \
  vendor/actions/gs702a/proprietary/lib/avd_avi.so:system/lib/avd_avi.so \
  vendor/actions/gs702a/proprietary/lib/avd_flv.so:system/lib/avd_flv.so \
  vendor/actions/gs702a/proprietary/lib/avd_mkv.so:system/lib/avd_mkv.so \
  vendor/actions/gs702a/proprietary/lib/avd_mp4.so:system/lib/avd_mp4.so \
  vendor/actions/gs702a/proprietary/lib/avd_mpg.so:system/lib/avd_mpg.so \
  vendor/actions/gs702a/proprietary/lib/avd_ogm.so:system/lib/avd_ogm.so \
  vendor/actions/gs702a/proprietary/lib/avd_rm.so:system/lib/avd_rm.so \
  vendor/actions/gs702a/proprietary/lib/avd_ts.so:system/lib/avd_ts.so \
  vendor/actions/gs702a/proprietary/lib/avd_wmv.so:system/lib/avd_wmv.so \
  vendor/actions/gs702a/proprietary/lib/id_jpg.so:system/lib/id_jpg.so \
  vendor/actions/gs702a/proprietary/lib/libACT_EncAPI.so:system/lib/libACT_EncAPI.so \
  vendor/actions/gs702a/proprietary/lib/libACT_FD.so:system/lib/libACT_FD.so \
  vendor/actions/gs702a/proprietary/lib/libACT_ISP.so:system/lib/libACT_ISP.so \
  vendor/actions/gs702a/proprietary/lib/libACT_V4L2HAL.so:system/lib/libACT_V4L2HAL.so \
  vendor/actions/gs702a/proprietary/lib/libactions_runtime.so:system/lib/libactions_runtime.so \
  vendor/actions/gs702a/proprietary/lib/libactions-ril.so:system/lib/libactions-ril.so \
  vendor/actions/gs702a/proprietary/lib/libalc.so:system/lib/libalc.so \
  vendor/actions/gs702a/proprietary/lib/libbacklight.so:system/lib/libbacklight.so \
  vendor/actions/gs702a/proprietary/lib/libc_malloc_debug_leak.so:system/lib/libc_malloc_debug_leak.so \
  vendor/actions/gs702a/proprietary/lib/libc_malloc_debug_qemu.so:system/lib/libc_malloc_debug_qemu.so \
  vendor/actions/gs702a/proprietary/lib/libctrlpt.so:system/lib/libctrlpt.so \
  vendor/actions/gs702a/proprietary/lib/libdmr.so:system/lib/libdmr.so \
  vendor/actions/gs702a/proprietary/lib/libdms.so:system/lib/libdms.so \
  vendor/actions/gs702a/proprietary/lib/libfacelock_jni.so:system/lib/libfacelock_jni.so \
  vendor/actions/gs702a/proprietary/lib/libffmpeg_wrapper.so:system/lib/libffmpeg_wrapper.so \
  vendor/actions/gs702a/proprietary/lib/libflint_engine_jni_api.so:system/lib/libflint_engine_jni_api.so \
  vendor/actions/gs702a/proprietary/lib/libGAL.so:system/lib/libGAL.so \
  vendor/actions/gs702a/proprietary/lib/libGLSLC.so:system/lib/libGLSLC.so \
  vendor/actions/gs702a/proprietary/lib/libgoogle_recognizer_jni.so:system/lib/libgoogle_recognizer_jni.so \
  vendor/actions/gs702a/proprietary/lib/libion.so:system/lib/libion.so \
  vendor/actions/gs702a/proprietary/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Audio.Decoder.so:system/lib/libOMX.Action.Audio.Decoder.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Image.Decoder.so:system/lib/libOMX.Action.Image.Decoder.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Video.Camera.so:system/lib/libOMX.Action.Video.Camera.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Video.Decoder.so:system/lib/libOMX.Action.Video.Decoder.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Video.Encoder.so:system/lib/libOMX.Action.Video.Encoder.so \
  vendor/actions/gs702a/proprietary/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
  vendor/actions/gs702a/proprietary/lib/libPopupVideo.so:system/lib/libPopupVideo.so \
  vendor/actions/gs702a/proprietary/lib/librs_jni.so:system/lib/librs_jni.so \
  vendor/actions/gs702a/proprietary/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
  vendor/actions/gs702a/proprietary/lib/libsrec_jni.so:system/lib/libsrec_jni.so \
  vendor/actions/gs702a/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
  vendor/actions/gs702a/proprietary/lib/libsub.so:system/lib/libsub.so \
  vendor/actions/gs702a/proprietary/lib/libusb-compat.so:system/lib/libusb-compat.so \
  vendor/actions/gs702a/proprietary/lib/libusb.so:system/lib/libusb.so \
  vendor/actions/gs702a/proprietary/lib/libvde_core.so:system/lib/libvde_core.so \
  vendor/actions/gs702a/proprietary/lib/libvideoeditor_core.so:system/lib/libvideoeditor_core.so \
  vendor/actions/gs702a/proprietary/lib/libvideoeditor_jni.so:system/lib/libvideoeditor_jni.so \
  vendor/actions/gs702a/proprietary/lib/libvideoeditor_osal.so:system/lib/libvideoeditor_osal.so \
  vendor/actions/gs702a/proprietary/lib/libvideoeditor_videofilters.so:system/lib/libvideoeditor_videofilters.so \
  vendor/actions/gs702a/proprietary/lib/libvideoeditorplayer.so:system/lib/libvideoeditorplayer.so \
  vendor/actions/gs702a/proprietary/lib/libvinit.so:system/lib/libvinit.so \
  vendor/actions/gs702a/proprietary/lib/libvoicesearch.so:system/lib/libvoicesearch.so \
  vendor/actions/gs702a/proprietary/lib/vd_flv1.so:system/lib/vd_flv1.so \
  vendor/actions/gs702a/proprietary/lib/vd_h263.so:system/lib/vd_h263.so \
  vendor/actions/gs702a/proprietary/lib/vd_h264.so:system/lib/vd_h264.so \
  vendor/actions/gs702a/proprietary/lib/vd_mjpg.so:system/lib/vd_mjpg.so \
  vendor/actions/gs702a/proprietary/lib/vd_mpeg.so:system/lib/vd_mpeg.so \
  vendor/actions/gs702a/proprietary/lib/vd_msm4.so:system/lib/vd_msm4.so \
  vendor/actions/gs702a/proprietary/lib/vd_rv34.so:system/lib/vd_rv34.so \
  vendor/actions/gs702a/proprietary/lib/vd_rvg2.so:system/lib/vd_rvg2.so \
  vendor/actions/gs702a/proprietary/lib/vd_vc1.so:system/lib/vd_vc1.so \
  vendor/actions/gs702a/proprietary/lib/vd_vp6.so:system/lib/vd_vp6.so \
  vendor/actions/gs702a/proprietary/lib/vd_vp8.so:system/lib/vd_vp8.so \
  vendor/actions/gs702a/proprietary/lib/vd_xvid.so:system/lib/vd_xvid.so \
  vendor/actions/gs702a/proprietary/lib/hw/camera.ATM702X.so:system/lib/hw/camera.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/sensors.ATM702X.so:system/lib/hw/sensors.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/lights.ATM702X.so:system/lib/hw/lights.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/hwcomposer.ATM702X.so:system/lib/hw/hwcomposer.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/hdmi.ATM702X.so:system/lib/hw/hdmi.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/gralloc.ATM702X.so:system/lib/hw/gralloc.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/gpuhwcomposer.ATM702X.so:system/lib/hw/gpuhwcomposer.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/displayengine.ATM702X.so:system/lib/hw/displayengine.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/cvbs.ATM702X.so:system/lib/hw/cvbs.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/plugins/com.adobe.flashplayer/libysshared.so:system/lib/plugins/com.adobe.flashplayer/libysshared.so \
  vendor/actions/gs702a/proprietary/lib/plugins/com.adobe.flashplayer/libflashplayer.so:system/lib/plugins/com.adobe.flashplayer/libflashplayer.so \
  vendor/actions/gs702a/proprietary/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so \
  vendor/actions/gs702a/proprietary/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so \
  vendor/actions/gs702a/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
  vendor/actions/gs702a/proprietary/usr/idc/ft5x0x_ts.idc:system/usr/idc/ft5x0x_ts.idc \
  vendor/actions/gs702a/proprietary/usr/idc/GT813.idc:system/usr/idc/GT813.idc \
  vendor/actions/gs702a/proprietary/usr/idc/mt395.idc:system/usr/idc/mt395.idc \
  vendor/actions/gs702a/proprietary/usr/keylayout/atc260x-adckeypad.kl:system/usr/keylayout/atc260x-adckeypad.kl \
  vendor/actions/gs702a/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
  vendor/actions/gs702a/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf
